### ISSUE TITLE
training json_csv_files for kinetics50

### ISSUE THREAD

**Issue by mj735** [XLearning-SCU/2024-ICLR-READ#5]
Excellent work! Could you please also upload the json_csv_files for the training dataset of kinetics50 (something like ks50_train_refer.json) ? Thanks!

**Comment by mouxingyang** [comment]
Thanks for your interest!

We have uploaded the requested ks50_train_refer.json.

**Comment by mj735** [comment]
Thanks! Is it convenient to also release the training code to get cav_mae_ks50.pth?

**Comment by mouxingyang** [comment]
I just followed the finetuning pipeline of [CAV-MAE](https://github.com/YuanGongND/cav-mae/blob/master/egs/vggsound/run_cavmae_ft.sh) on the VGGSound dataset to get cav_mae_ks50.pth. The main modification is that I replaced the weight file with the one from the KS50 dataset. For usage, you can directly access the finetuned checkpoint that has been uploaded.

Due to recent brainstorming sessions, I haven't had the time to reshape the finetuning code to produce `cav_mae_ks50.pth`. I plan to release that part of the code at a later date.

Let me know if there's anything else you'd like to know.

**Comment by mj735** [comment]
Thanks for your reply! The **audio_train256.tar.gz** you uploaded on BaiduPan only has 23974 files, which is not complete (29204 in your paper). Could you please unload the complete data?

**Comment by mouxingyang** [comment]
Sorry for the compression bug. The link of NEW [audio_train256.tar.gz](https://pan.baidu.com/s/17E0I1X2aSBHhvU3Xsw4OEA?pwd=tw35) is updated :)
